version: "3.5"

services:
  dogpass-postgres:
    container_name: dogpass-postgres
    image: postgres:13
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - db_volume:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS localhost:5432/ping || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 20

volumes:
  db_volume:
  logs_volume:
